CREATE TABLE AUTHOR(
	AUTHOR_ID char(4) primary key not null,
	LASTNAME nvarchar(24),
	FIRSTNAME nvarchar(24),
	EMAIL nvarchar(24),
	CITY nvarchar(24),
	COUNTRY nvarchar(24),
	TELEPHONE_NUMBER CHAR(20)
);
INSERT INTO AUTHOR
VALUES
('1001','THOMAS','JOHN','JOHNT@...','NEW YORK','USA','555-0001'),
('1002','JAMES','ALICE','ALICEJ@...','SEATLE','USA','555-0002'),
('1003','WELLS','STEVE','STEVEW@...','MONTREAL','CANADA','555-0003'),
('1004','KUMAR','SANTOSH','KUMARS@...','LONDON','UK','555-0004');


--ALTER TABLE  AUTHOR DROP COLUMN TELEPHONE_NUMBER;
--ALTER TABLE AUTHOR ALTER COLUMN TELEPHONE_NUMBER SET DATA TYPE CHAR(40);
TRUNCATE TABLE AUTHOR IMMEDIATE;

SELECT * FROM AUTHOR;
DROP TABLE AUTHOR;